### ISSUE TITLE
Epic: Week 1 MVP

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/kaguya_spectral_profiler#17]
- [ ] Stand up HBase
- [ ] Stand up PG
- [ ] Determine PG Schema for meta data lookups
- [ ] Determine HBase schema for metadata lookups
- [ ] Load 10k in PG
- [ ] Load 10k in HB
- [ ] Check file hashes
  - [ ] Data Volume
  - [ ] Simplification: How much is viable? RPC? 
- [ ] Run metadata query - PG
- [ ] Run metadata query - HB
- [ ] PG - Array vs JSON
- [ ] HB - How to store spectra?
- [ ] STRETCH: Spatial
